####################################################################################################
#                                        test_win_basis.py                                         #
####################################################################################################
#                                                                                                  #
# Purpose: Tests for core/win_basis.py without the network: the generate.py options in both        #
#          recorded formats, TE (single value and sLASER TE1/TE2/TE3 list), loading a basis folder #
#          (non-basis JSON skipped) and refusing Git LFS pointer files.                            #
#                                                                                                  #
####################################################################################################

from __future__ import annotations

import json
import os
import sys

import pytest

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from basisremy.core import externals, win_basis


def test_options_json_dict():
    desc = ('7T MEGA-edited sLASER sequence, CMRR.Generated by generate.py in /x.Options: '
            '{"output": "mslaser_78_res10", "te": "78.0", "edit_ppm": "[7.0, 1.9]"}.')
    opts = win_basis.options(desc)
    assert opts['output'] == 'mslaser_78_res10' and win_basis.te_ms(opts) == 78.0


def test_options_key_value_list():
    desc = ('PRESS.Generated by generate.py.Options: output=test, te=35.0, te1=0.0, '
            'refocus_type=mao, tx_offset=-2.0, b0=2.89, resolution=15.')
    opts = win_basis.options(desc)
    assert opts['refocus_type'] == 'mao' and opts['tx_offset'] == '-2.0' and opts['resolution'] == '15'
    assert win_basis.te_ms(opts) == 35.0


def test_te_slaser_list_and_missing():
    assert win_basis.te_ms({'te': '[8.0, 12.0, 10.0]'}) == 30.0
    assert win_basis.te_ms({'output': 'test'}) is None
    assert win_basis.options('no options recorded') == {}


@pytest.fixture
def repo(tmp_path, monkeypatch):
    """A fake checked-out WIN repository; git calls are recorded, not run."""
    calls = []
    monkeypatch.setattr(externals, 'ensure', lambda name: str(tmp_path))
    monkeypatch.setattr(win_basis, '_git', lambda *a: calls.append(a) or '')
    folder = tmp_path / 'basis_sets' / 'seq' / 'te30'
    folder.mkdir(parents=True)
    return folder, calls


def test_load_skips_non_basis_json(repo):
    folder, calls = repo
    (folder / 'NAA.json').write_text(json.dumps({
        'seq': {'B0': 2.89}, 'spinSys': {'name': 'NAA'},
        'basis': {'basis_re': [1.0, 0.5], 'basis_im': [0.0, -0.5], 'basis_dwell': 1 / 6000,
                  'basis_centre': 123.2, 'basis_name': 'NAA'}}))
    (folder / 'systest.json').write_text(json.dumps({'sysNAA': {}}))
    out = win_basis.load('basis_sets/seq/te30')
    assert list(out) == ['NAA']
    assert out['NAA']['fid'].tolist() == [1 + 0j, 0.5 - 0.5j] and out['NAA']['seq']['B0'] == 2.89
    assert ('sparse-checkout', 'add', 'basis_sets/seq/te30') in calls


def test_fetch_refuses_lfs_pointer(repo):
    folder, _ = repo
    (folder / 'NAA.json').write_text('version https://git-lfs.github.com/spec/v1\noid sha256:ab\nsize 1\n')
    with pytest.raises(externals.ExternalFetchError, match='pointer'):
        win_basis.fetch('basis_sets/seq/te30')
