####################################################################################################
#                                         pulse_library.py                                         #
####################################################################################################
#                                                                                                  #
# Authors: J. P. Merkofer (j.p.merkofer@tue.nl)                                                    #
#                                                                                                  #
# Created: 01/10/26                                                                                #
#                                                                                                  #
# Purpose: Generate standard RF pulse waveforms (no vendor file needed) and write them in the      #
#          formats the simulation engines read. Waveforms are FID-A matrices [phase deg,           #
#          amplitude 0..1, time step, (gradient G/cm)] so they go through the same loader and      #
#          B1 scaling as a vendor file (io_loadRFwaveform / core.rf_pulses).                       #
#                                                                                                  #
#          Shapes: sinc, Gaussian (FID-A rf_gauss, calibrated to its inversion FWHM), HSn          #
#          (Silver 1984; Tannus & Garwood 1997), GOIA-WURST / GOIA-HS / FOCI (Tannus & Garwood     #
#          1997; Andronesi et al. JMR 2010; Kinchesh 2005), following FID-A's rf_hs / rf_goia and  #
#          the CMRR universal-sLASER formulation. A named catalogue of "standard pulses"           #
#          (STANDARD) resolves a 'standard:<name>' value of 'Path to Pulse' / 'Edit Pulse Path'    #
#          to a generated file in the run's workdir.                                               #
#                                                                                                  #
####################################################################################################

from __future__ import annotations

import math
import os
from dataclasses import dataclass, field

import numpy as np

from basisremy.core.rf_pulses import scale_waveform

GYRO_HZ_PER_G = 4257.7          # 1H, as in FID-A rf_goia / rf_hs

PREFIX = 'standard:'            # marker in a pulse-path parameter


#**************************************************************************************************#
#                                            waveform                                              #
#**************************************************************************************************#
@dataclass
class Pulse:
    """A generated RF pulse in FID-A's waveform convention.

    waveform: (N, 3) or (N, 4) array [phase deg, amplitude 0..1, step, gradient G/cm].
    kind: 'exc', 'ref' or 'inv' (how the engines scale B1).
    tp_ms: design duration; bw_hz: design bandwidth (frequency selective) or
    the design slice thickness thk_cm for gradient-modulated pulses.
    """
    name: str
    waveform: np.ndarray
    kind: str
    tp_ms: float
    bw_hz: float | None = None
    thk_cm: float | None = None
    meta: dict = field(default_factory=dict)

    @property
    def is_gradient_modulated(self) -> bool:
        return self.waveform.shape[1] > 3 and bool(np.any(self.waveform[:, 3]))

    @property
    def n(self) -> int:
        return int(self.waveform.shape[0])

    # ---- writers ---------------------------------------------------------------
    def write(self, path: str) -> str:
        """Write in the format given by the extension (.pta / .RF / .txt)."""
        ext = os.path.splitext(path)[1].lower()
        if ext == '.pta':
            return self.to_pta(path)
        if ext == '.rf':
            return self.to_rf(path)
        if ext == '.txt':
            return self.to_txt(path)
        raise ValueError(f"Unsupported pulse file extension '{ext}' (use .pta, .RF or .txt)")

    def to_pta(self, path: str) -> str:
        """Siemens .pta (FID-A io_writepta layout): amplitude 0..1, phase rad."""
        if self.is_gradient_modulated:
            raise ValueError(f"{self.name}: .pta cannot carry the gradient waveform; write .txt")
        amp = self.waveform[:, 1] / np.max(self.waveform[:, 1])
        ph = np.mod(np.deg2rad(self.waveform[:, 0]), 2 * np.pi)
        cplx = amp * np.exp(1j * ph)
        lines = [f"PULSENAME:\t{self.name}",
                 "COMMENT:\tStandard pulse generated by BasisREMY (basisremy.core.pulse_library)",
                 "REFGRAD:\t1.000000",
                 "MINSLICE:\t1.000000000", "MAXSLICE:\t200.000000000",
                 f"AMPINT:\t{abs(np.sum(cplx)):.6f}",
                 f"POWERINT:\t{np.sum(np.abs(cplx) ** 2):.6f}",
                 f"ABSINT:\t{np.sum(np.abs(cplx)):.6f}", ""]
        lines += [f"{a:.9f}\t{p:.9f}\t; ({i})" for i, (a, p) in enumerate(zip(amp, ph))]
        with open(path, 'w') as f:
            f.write("\n".join(lines) + "\n")
        return path

    def to_rf(self, path: str) -> str:
        """Varian/Agilent .RF (FID-A io_writeRF layout): phase deg, amplitude 0..1023, gate."""
        if self.is_gradient_modulated:
            raise ValueError(f"{self.name}: .RF cannot carry the gradient waveform; write .txt")
        amp = 1023.0 * self.waveform[:, 1] / np.max(self.waveform[:, 1])
        with open(path, 'w') as f:
            f.write(f"# {self.name}\n# Standard pulse generated by BasisREMY\n"
                    f"# number of points = {self.n}\n# TYPE selective\n")
            for p, a in zip(self.waveform[:, 0], amp):
                f.write(f"{p:.3f}\t{a:.1f}\t1.0\n")
        return path

    def to_txt(self, path: str) -> str:
        """FID-A basic .txt: amplitude, phase deg, step[, gradient G/cm] (io_readRFtxt order)."""
        cols = [self.waveform[:, 1], self.waveform[:, 0], self.waveform[:, 2]]
        if self.waveform.shape[1] > 3:
            cols.append(self.waveform[:, 3])
        np.savetxt(path, np.column_stack(cols), fmt='%.9f')
        return path

    def to_fslmrs(self, tp_ms: float | None = None, flip=None, grad_mt_per_m=0.0) -> dict:
        """FSL-MRS denmatsim RF block: amp in Hz, phase in rad, time in s, grad mT/m.

        A gradient-modulated pulse writes its shape into 'grad' (3 x N, x axis);
        the slice gradient amplitude for the wanted thickness is grad_mt_per_m.
        """
        tp = float(tp_ms if tp_ms is not None else self.tp_ms) / 1000.0
        phase, amp_hz, dt = scale_waveform(self.waveform, tp, flip or self.kind)
        if self.is_gradient_modulated:
            g = self.waveform[:, 3] / np.max(np.abs(self.waveform[:, 3])) * float(grad_mt_per_m)
            grad = [g.tolist(), [0.0] * self.n, [0.0] * self.n]
        else:
            grad = [float(grad_mt_per_m), 0.0, 0.0]
        return {'time': tp, 'frequencyOffset': 0, 'phaseOffset': 0,
                'amp': amp_hz.tolist(), 'phase': np.deg2rad(phase).tolist(), 'grad': grad}

    def to_array(self, tp_ms: float | None = None, flip=None):
        """(complex B1 in Hz, dwell times in s[, gradient G/cm]) for spant / Spinach workers."""
        tp = float(tp_ms if tp_ms is not None else self.tp_ms) / 1000.0
        phase, amp_hz, dt = scale_waveform(self.waveform, tp, flip or self.kind)
        b1 = amp_hz * np.exp(1j * np.deg2rad(phase))
        if self.is_gradient_modulated:
            return b1, dt, self.waveform[:, 3].copy()
        return b1, dt


#**************************************************************************************************#
#                                            generators                                            #
#**************************************************************************************************#
def _matrix(phase_deg, amp, grad=None):
    amp = np.asarray(amp, dtype=float)
    cols = [np.asarray(phase_deg, dtype=float), amp / np.max(np.abs(amp)), np.ones(amp.size)]
    if grad is not None:
        cols.append(np.asarray(grad, dtype=float))
    return np.column_stack(cols)


def sinc(lobes: int = 3, n: int = 256, kind: str = 'ref', apodise: bool = True,
         tp_ms: float = 5.0) -> Pulse:
    """Sinc with `lobes` lobes (FID-A rf_sinc), optional Hanning apodisation."""
    if lobes < 1:
        raise ValueError("sinc: at least one lobe")
    t = np.linspace(-(0.5 + lobes / 2), 0.5 + lobes / 2, n)
    am = np.sinc(t)
    if apodise:
        am = am * (0.5 + 0.5 * np.cos(np.pi * t / t[-1]))
    phase = 180.0 * (am < 0)
    return Pulse(f'sinc{lobes}_{kind}', _matrix(phase, np.abs(am)), kind, tp_ms,
                 meta={'lobes': lobes, 'apodise': apodise})


def gauss(tp_ms: float, bw_hz: float, n: int = 256, kind: str = 'inv',
          calibrate: bool = True) -> Pulse:
    """Gaussian whose inversion profile has FWHM `bw_hz`, on resonance.

    FID-A's rf_gauss sets the time-domain FWHM to 1/bw, which gives a measured
    inversion FWHM of about 0.7 bw at 180 degrees; with `calibrate` the width is
    corrected against the Bloch profile so the measured FWHM equals `bw_hz`.
    The pulse is kept on resonance: the engines apply the editing offset
    themselves (rf_freqshift, FSL-MRS phase ramp) after scaling B1, and the
    loaders' on-resonance B1 search would over-drive a pre-shifted pulse.
    """
    tps = tp_ms / 1000.0
    t = np.linspace(-tps / 2 + tps / (2 * n), tps / 2 - tps / (2 * n), n)
    width = 1.0 / bw_hz                                     # time-domain FWHM (rf_gauss)
    for _ in range(4 if calibrate else 1):
        c = width / (2 * math.sqrt(2 * math.log(2)))
        env = np.exp(-t ** 2 / (2 * c ** 2))
        p = Pulse('gauss', _matrix(np.zeros(n), env), kind, tp_ms)
        if not calibrate:
            break
        measured = bandwidth_hz(p, span_hz=4 * bw_hz, points=2001)
        if abs(measured - bw_hz) < 0.01 * bw_hz:
            break
        width *= measured / bw_hz                            # wider in time -> narrower band
    return Pulse(f'gauss_{tp_ms:g}ms_{bw_hz:g}Hz', _matrix(np.zeros(n), env), kind, tp_ms,
                 bw_hz=bw_hz, meta={'fwhm_t_s': width})


def hsn(tp_ms: float, tbw: float, order: int = 1, n: int = 512, trunc: float = 0.01,
        kind: str = 'inv') -> Pulse:
    """HSn adiabatic pulse (rf_hs): AM = sech(beta tau^n), FM = integral of AM^2 (Tannus & Garwood).

    FID-A's rf_hs integrates AM, not AM^2; the hsn.py of the WIN basis sets and
    the offset-independent-adiabaticity rule use AM^2. The latter is used here.
    """
    n += n % 2
    tps = tp_ms / 1000.0
    t = np.linspace(0.0, tps, n)
    tau = 2 * t / tps - 1
    beta = math.acosh(1.0 / trunc)
    am = 1.0 / np.cosh(beta * tau ** order)
    fm = _cumtrapz(am ** 2, t)
    fm -= fm[n // 2]
    fm = fm / np.max(np.abs(fm)) * (tbw / tps) / 2.0          # Hz, sweep +-bw/2
    phase = np.rad2deg(2 * np.pi * _cumtrapz(fm, t))
    return Pulse(f'hs{order}_R{tbw:g}', _matrix(phase, am), kind, tp_ms, bw_hz=tbw / tps,
                 meta={'order': order, 'tbw': tbw, 'trunc': trunc})


def goia(tp_ms: float, tbw: float, thk_cm: float, shape: str = 'wurst', n_am: int = 16,
         m_gm: int = 4, f: float = 0.9, n: int = 512, trunc: float = 0.01, kind: str = 'ref',
         gmax_g_per_cm: float = 4.0) -> Pulse:
    """Gradient-modulated offset-independent adiabatic pulse (GOIA-WURST / GOIA-HS / FOCI).

    AM, GM and FM follow Andronesi et al. 2010 (WURST), Tannus & Garwood 1997
    (HS) and Kinchesh & Ordidge 2005 (FOCI), as in the CMRR universal-sLASER
    design code. The gradient column is the shape in G/cm for the design slice
    `thk_cm`; FID-A's rf_scaleGrad rescales it to the simulated thickness.
    """
    n += n % 2
    tps = tp_ms / 1000.0
    t = np.linspace(0.0, tps, n)
    tau = 2 * t / tps - 1
    beta = math.acosh(1.0 / trunc)
    sech = lambda x: 1.0 / np.cosh(x)                       # noqa: E731
    shape = shape.lower()
    if shape == 'wurst':
        am = 1.0 - np.abs(np.sin(np.pi / 2 * tau)) ** n_am
        gm = (1.0 - f) + f * np.abs(np.sin(np.pi / 2 * tau)) ** m_gm
    elif shape == 'hs':
        am = sech(beta * tau ** n_am)
        gm = 1.0 - f * sech(beta * tau ** m_gm)
    elif shape == 'foci':
        ff = 10.0                                            # C-shaped, Kinchesh 2005
        aa = np.where(np.cosh(beta * tau) < ff, np.cosh(beta * tau), ff)
        am = aa * sech(beta * tau)
        gm = aa / ff
    else:
        raise ValueError(f"goia: shape must be 'wurst', 'hs' or 'foci', not '{shape}'")
    fm = gm * (_cumtrapz(am ** 2 / gm, t) - _cumtrapz(am ** 2 / gm, t)[n // 2])
    fm = fm / np.max(np.abs(fm)) * (tbw / tps) / 2.0          # Hz
    phase = np.rad2deg(2 * np.pi * _cumtrapz(fm, t))
    g_design = (tbw / tps) / (GYRO_HZ_PER_G * thk_cm)         # G/cm for the design slice
    if g_design > gmax_g_per_cm:
        raise ValueError(f"goia: {g_design:.2f} G/cm exceeds gmax {gmax_g_per_cm} G/cm "
                         f"(raise thk_cm or tp_ms, lower tbw)")
    return Pulse(f'goia-{shape}_{tp_ms:g}ms_R{tbw:g}', _matrix(phase, am, gm * g_design), kind,
                 tp_ms, bw_hz=tbw / tps, thk_cm=thk_cm,
                 meta={'shape': shape, 'n': n_am, 'm': m_gm, 'f': f, 'tbw': tbw})


def _cumtrapz(y, x):
    out = np.zeros_like(y, dtype=float)
    out[1:] = np.cumsum(0.5 * (y[1:] + y[:-1]) * np.diff(x))
    return out


#**************************************************************************************************#
#                                          Bloch profile                                           #
#**************************************************************************************************#
def bloch_profile(pulse: Pulse, offsets_hz, tp_ms: float | None = None, w1max_hz: float | None = None):
    """Magnetisation (Mx, My, Mz) after the pulse vs frequency offset, M0 = +z, no gradient.

    w1max defaults to the engines' own scaling for the pulse kind (scale_waveform).
    """
    tp = float(tp_ms if tp_ms is not None else pulse.tp_ms) / 1000.0
    phase, amp_hz, dt = scale_waveform(pulse.waveform, tp, pulse.kind)
    if w1max_hz is not None:
        amp_hz = amp_hz / np.max(amp_hz) * w1max_hz
    off = np.asarray(offsets_hz, dtype=float)
    m = np.zeros((3, off.size)); m[2] = 1.0
    for ph_d, a, d in zip(phase, amp_hz, dt):
        ph = math.radians(ph_d)
        bx, by, bz = a * math.cos(ph), a * math.sin(ph), off           # Hz
        bmag = np.sqrt(bx ** 2 + by ** 2 + bz ** 2)
        theta = 2 * np.pi * bmag * d
        ux, uy, uz = bx / np.where(bmag > 0, bmag, 1), by / np.where(bmag > 0, bmag, 1), bz / np.where(bmag > 0, bmag, 1)
        c, s = np.cos(theta), np.sin(theta)
        dot = ux * m[0] + uy * m[1] + uz * m[2]
        m = np.array([m[0] * c + (uy * m[2] - uz * m[1]) * s + ux * dot * (1 - c),
                      m[1] * c + (uz * m[0] - ux * m[2]) * s + uy * dot * (1 - c),
                      m[2] * c + (ux * m[1] - uy * m[0]) * s + uz * dot * (1 - c)])
    return m


def bandwidth_hz(pulse: Pulse, tp_ms: float | None = None, span_hz: float = 20000.0,
                 points: int = 4001) -> float:
    """Bandwidth as FID-A measures it: Mz < 0 (ref/inv) or |Mxy| > 0.5 (exc) extent."""
    off = np.linspace(-span_hz, span_hz, points)
    m = bloch_profile(pulse, off, tp_ms)
    sel = (np.abs(m[0] + 1j * m[1]) > 0.5) if pulse.kind == 'exc' else (m[2] < 0)
    idx = np.where(sel)[0]
    return float(off[idx[-1]] - off[idx[0]]) if idx.size else 0.0


#**************************************************************************************************#
#                                        standard catalogue                                        #
#**************************************************************************************************#
# name -> (factory, file extension). Durations are the published defaults; the
# backends still apply their own 'RefTp' / 'Edit Tp' when scaling B1.
STANDARD = {
    # amplitude modulated (frequency selective), .pta
    # lobes chosen so the time-bandwidth product matches FID-A's sample pulses /
    # the Siemens Mao refocusing pulse (TBW 5.7; 7 lobes apodised = 5.6) and the
    # sample excitation pulse (4.4 kHz at 2 ms; 7 lobes apodised = 3.9 kHz)
    'sinc-exc':    (lambda: sinc(7, kind='exc', tp_ms=2.0), '.pta'),
    'sinc-ref':    (lambda: sinc(7, kind='ref', tp_ms=5.0), '.pta'),
    'gauss-edit':  (lambda: gauss(14.0, 88.0, kind='inv'), '.pta'),       # MEGA editing, 14 ms / 88 Hz
    'gauss-edit-20ms': (lambda: gauss(20.0, 62.0, kind='inv'), '.pta'),   # HERMES/HERCULES style, 20 ms
    # adiabatic, frequency selective, .pta
    'hs1-inv':     (lambda: hsn(5.0, 15.0, order=1, kind='inv'), '.pta'),
    'hs4-ref':     (lambda: hsn(3.5, 25.0, order=4, kind='ref'), '.pta'),  # HS4R25 (Oz & Tkac)
    # gradient modulated, .txt (amplitude, phase, step, gradient)
    'goia-wurst':  (lambda: goia(4.5, 45.0, 2.0, 'wurst', kind='ref'), '.txt'),  # 10 kHz / 4.5 ms
    'goia-hs':     (lambda: goia(4.5, 45.0, 2.0, 'hs', kind='ref'), '.txt'),
    'foci':        (lambda: goia(4.5, 45.0, 2.0, 'foci', kind='ref'), '.txt'),
}


def is_standard(spec) -> bool:
    return isinstance(spec, str) and spec.strip().lower().startswith(PREFIX)


def standard_name(spec: str) -> str:
    name = spec.strip()[len(PREFIX):].strip().lower()
    if name not in STANDARD:
        raise ValueError(f"Unknown standard pulse '{name}'. Available: {', '.join(STANDARD)}")
    return name


def make_standard(name: str) -> Pulse:
    return STANDARD[name][0]()


def resolve_pulse(spec, workdir: str) -> str:
    """'standard:<name>' -> generated file in workdir; any other value is returned unchanged."""
    if not is_standard(spec):
        return spec
    name = standard_name(spec)
    factory, ext = STANDARD[name]
    path = os.path.join(workdir, f'std_{name}{ext}')
    if not os.path.exists(path):
        factory().write(path)
    return path


def siemens_refocusing(pulse_names):
    """Standard refocusing pulse and duration for the pulse slots a Siemens twix header names
    (sTXSPEC.aRFPULSE[].tName; no waveforms or durations there). Only the hyperbolic-secant
    family (CMRR semi-LASER 'hsn_sl' / 'hsn_ph') differs from the backends' defaults; None
    otherwise."""
    if any(str(n).lower().startswith('hsn') for n in pulse_names or ()):
        return 'standard:hs4-ref', 3.5
    return None
